services:
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    networks:
      - backend-network
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: postgres:16.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d amulet"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - 5432:5432
networks:
  backend-network:
