name: Lint and Test

# Controls when the action will run.
on:
  # Triggers the workflow pull request events but only for the main and develop branch
  pull_request:
    branches: [main, develop, staging]
    
  push:
    branches: [main, develop, staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Check linter, unit and e2e tests.
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install Node LTS Jod
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/jod'
          cache: 'npm'

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    
      - name: Npm Cache
        uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Audit
        run: npm audit --audit-level=high --prod

      - name: Install dependencies from lock.
        run: npm ci

      - name: Linter.
        run: npm run lint:ci

      - name: Unit tests.
        run: npm run test:cov

      - name: Build source code.
        run: npm run build